zig:
	zig build-exe -fPIC -OReleaseFast test_sxs.zig

# -flto error: LTO is not yet supported with the Mach-O object format. More details: https://github.com/ziglang/zig/issues/8680

clean:
	rm *.o test_sxs